app = "starpulse-relay"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3737
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "starpulse_data"
  destination = "/app/data"
